export {default as Home} from './Home/Home'
export {default as Header} from './Header/Header'
export {default as Navigation} from './Header/Navigation'
export {default as Viewers} from './Viewers/Viewers'
export {default as ImageSlider} from './Slider/ImageSlider'
export {default as Movies} from './Movies/Movies'
export {default as Details} from './Details/Details'